# Please refer https://aka.ms/HTTPSinContainer on how to setup an https developer certificate for your ASP.NET Core service.

version: '3.4'

services:
  client:
    image: client
    build:
      context: .
      dockerfile: Client/Dockerfile
    ports:
      - 8080:8080

  server:
    image: server
    build:
      context: .
      dockerfile: Server/Dockerfile
    ports:
      - 8081:8080
